# Usa la imagen base de Nginx desde Alpine Linux
FROM nginx:alpine

# Copia el contenido del directorio 'frontend' a la carpeta HTML de Nginx
COPY index.html /usr/share/nginx/html

# Expone el puerto 80 para que Nginx pueda servir el contenido
EXPOSE 80
