apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: music
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 8080
        env:
          - name: YOUTUBE_API_KEY
            valueFrom:
              secretKeyRef:
                name: youtube-api-secret
                key: api-key
