backend:
  replicaCount: 1
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 83652d703969fbbfe77e8e98bd56463b6af88d58

frontend:
  replicaCount: 2
  image:
    repository: jaimehenao8126/globant-frontend
    tag: 83652d703969fbbfe77e8e98bd56463b6af88d58

service:
  type: ClusterIP
  port: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1