backend:
  replicaCount: 1
  image:
    repository: jaimehenao8126/music-frontend
    tag: 53d770248433de733ed322789e13395f7c308e58

frontend:
  replicaCount: 2
  image:
    repository: jaimehenao8126/music-frontend
    tag: 53d770248433de733ed322789e13395f7c308e58

service:
  type: ClusterIP
  port: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1