backend:
  replicaCount: 1
  image:
    repository: jaimehenao8126/music-frontend
    tag: 8e3de6ee2f53f42b10acd422e38aadc0b38d110c

frontend:
  replicaCount: 2
  image:
    repository: jaimehenao8126/music-frontend
    tag: 8e3de6ee2f53f42b10acd422e38aadc0b38d110c

service:
  type: ClusterIP
  port: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1