# values.yaml

backend:
  replicaCount: 2
  image:
    repository: jaimehena8126/music-backend
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

frontend:
  replicaCount: 2
  image:
    repository: jaimehena8126/music-frontend
    tag: "v1.0.0"
    pullPolicy: IfNotPresent

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1
